/* Ergonomic aliases over the OpenAPI types generated by `npm run generate:api`. */
import type { components } from "./openapi";

export type AnalysisRequest = components["schemas"]["AnalysisRequest"];
export type AnalysisResponse = components["schemas"]["AnalysisResponse"];
export type LocationResult = components["schemas"]["LocationResult"];
export type Competitor = components["schemas"]["Competitor"];
export type ForecastDriver = components["schemas"]["ForecastDriver"];
export type ProjectionMonth = components["schemas"]["ProjectionMonth"];
export type DataFreshness = components["schemas"]["DataFreshness"];
export type StoreType = AnalysisRequest["store_type"];
export type ScenarioMode = AnalysisRequest["scenario_mode"];
