/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Location Search */
        get: operations["location_search_api_locations_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_api_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Store Type
             * @enum {string}
             */
            store_type: "Cafe" | "Convenience Store" | "Restaurant" | "Bakery" | "Pharmacy" | "Gym";
            /** Avg Sale Price */
            avg_sale_price: number;
            /** Staff Count */
            staff_count: number;
            /** Monthly Wage */
            monthly_wage: number;
            /** Hours Of Work */
            hours_of_work: number;
            /** Cost Of Goods Pct */
            cost_of_goods_pct: number;
            /** Extra Cost */
            extra_cost: number;
            /** Rent Override */
            rent_override?: number | null;
            /**
             * Scenario Mode
             * @default base
             * @enum {string}
             */
            scenario_mode: "base" | "conservative" | "optimistic";
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Store Type
             * @enum {string}
             */
            store_type: "Cafe" | "Convenience Store" | "Restaurant" | "Bakery" | "Pharmacy" | "Gym";
            /**
             * Scenario Mode
             * @enum {string}
             */
            scenario_mode: "base" | "conservative" | "optimistic";
            /** Model Version */
            model_version: string;
            /** Avg Sale Price */
            avg_sale_price: number;
            /** Staff Count */
            staff_count: number;
            /** Monthly Wage */
            monthly_wage: number;
            /** Hours Of Work */
            hours_of_work: number;
            /** Cost Of Goods Pct */
            cost_of_goods_pct: number;
            /** Labor Cost */
            labor_cost: number;
            /** Cost Of Goods Cost */
            cost_of_goods_cost: number;
            /** Rent Cost */
            rent_cost: number;
            /** Extra Cost */
            extra_cost: number;
            /** Total Cost */
            total_cost: number;
            /** Industry Base Revenue */
            industry_base_revenue: number;
            /** Capacity Revenue */
            capacity_revenue: number;
            /** Base Revenue */
            base_revenue: number;
            /** Competitors */
            competitors: components["schemas"]["Competitor"][];
            /**
             * Rent Source
             * @enum {string}
             */
            rent_source: "estimated" | "manual";
            rent_assumptions: components["schemas"]["RentAssumptions"];
            /** Competitor Count */
            competitor_count: number;
            /** Nearest Distance */
            nearest_distance: number | null;
            /** Cannibalization Multiplier */
            cannibalization_multiplier: number;
            /** Foot Traffic Multiplier */
            foot_traffic_multiplier: number;
            /** Revenue Min */
            revenue_min: number;
            /** Central Estimate */
            central_estimate: number;
            /** Revenue Max */
            revenue_max: number;
            /** Twenty Percent Buffer */
            twenty_percent_buffer: number;
            /** Rating */
            rating: string;
            /** Rating Color */
            rating_color: string;
            /** Rating Detail */
            rating_detail: string;
            /** Rating Reasons */
            rating_reasons: string[];
            /** Forecast Drivers */
            forecast_drivers: components["schemas"]["ForecastDriver"][];
            /** Assumptions Summary */
            assumptions_summary: string;
            data_freshness: components["schemas"]["DataFreshness"];
            /** Profit Projection */
            profit_projection: components["schemas"]["ProjectionMonth"][];
        };
        /** Competitor */
        Competitor: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Distance M */
            distance_m: number;
        };
        /** DataFreshness */
        DataFreshness: {
            /** Source */
            source: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Cache Status
             * @enum {string}
             */
            cache_status: "live" | "fresh_cache";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ForecastDriver */
        ForecastDriver: {
            /** Label */
            label: string;
            /** Effect */
            effect: string;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationResult */
        LocationResult: {
            /** Display Name */
            display_name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** ProjectionMonth */
        ProjectionMonth: {
            /** Month */
            month: number;
            /** Revenue */
            revenue: number;
            /** Profit */
            profit: number;
        };
        /** RentAssumptions */
        RentAssumptions: {
            /** Distance To Cbd Km */
            distance_to_cbd_km: number;
            /** Annual Rent Per Sqm */
            annual_rent_per_sqm: number;
            /** Assumed Floor Area Sqm */
            assumed_floor_area_sqm: number;
            /** Estimated Monthly Rent */
            estimated_monthly_rent: number;
            /** Manual Monthly Rent */
            manual_monthly_rent?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    location_search_api_locations_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
