import type { CSSProperties } from "react";
import { Info, Plus } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AnalysisResponse } from "./api/generated";
import type { LocationSelection } from "./scenario";
import { SiteMap } from "./SiteMap";

const nzd = (value: number) => new Intl.NumberFormat("en-NZ", { style: "currency", currency: "NZD", maximumFractionDigits: 0 }).format(value);
export function ForecastResult({ analysis, location, onRestart }: { analysis: AnalysisResponse; location: LocationSelection; onRestart: () => void }) {
  const costs = [{ name: "Labor", value: analysis.labor_cost, color: "#2563EB" }, { name: "Cost of goods", value: analysis.cost_of_goods_cost, color: "#F59E0B" }, { name: "Rent", value: analysis.rent_cost, color: "#8B5CF6" }, { name: "Extra", value: analysis.extra_cost, color: "#F97316" }];
  const nearest = analysis.competitors.slice(0, 5); const distanceBands = { close: analysis.competitors.filter(item => item.distance_m < 100).length, nearby: analysis.competitors.filter(item => item.distance_m >= 100 && item.distance_m < 500).length, wider: analysis.competitors.filter(item => item.distance_m >= 500).length };
  return <main className="result-page"><header className="result-header"><div><p className="eyebrow">FUTURE VIABILITY FORECAST</p><h1>{analysis.store_type} site assessment</h1><p className="subtitle">{location.kind === "unselected" ? "Selected Auckland site" : location.displayName} · {analysis.scenario_mode} future</p></div><button className="back-button" onClick={onRestart}>New scenario <Plus size={18} /></button></header><section className="bento-grid">
    <div className="rating-panel panel" style={{ "--rating-color": analysis.rating_color } as CSSProperties}><p>FUTURE FEASIBILITY RATING</p><h2>{analysis.rating}</h2><span>{analysis.rating_detail}</span><ul className="rating-reasons">{analysis.rating_reasons.map(reason => <li key={reason}>{reason}</li>)}</ul></div>
    <div className="metrics"><div className="metric revenue"><p>{analysis.scenario_mode} monthly forecast</p><strong>{nzd(analysis.revenue_min)} – {nzd(analysis.revenue_max)}</strong><span>Today’s data, tomorrow’s decision.</span></div><div className="metric"><p>Central estimate</p><strong>{nzd(analysis.central_estimate)}</strong></div><div className="metric"><p>Break-even point</p><strong>{nzd(analysis.total_cost)}</strong></div><div className="metric"><p>Live competitors</p><strong>{analysis.competitor_count}</strong></div></div>
    <div className="forecast-story panel"><div><p className="eyebrow">MODEL TRANSPARENCY</p><h2>Why this future view?</h2><p>{analysis.assumptions_summary}</p></div><div className="driver-list">{analysis.forecast_drivers.map(driver => <article key={driver.label}><strong>{driver.label}</strong><span>{driver.effect}</span><p>{driver.detail}</p></article>)}</div><p className="freshness"><Info size={16} /> {analysis.data_freshness.cache_status === "live" ? "Live data" : analysis.data_freshness.cache_status === "fresh_cache" ? "Fresh cached data" : "Fallback cached data — live competitor data is temporarily unavailable"} from {analysis.data_freshness.source}; refreshed {new Date(analysis.data_freshness.fetched_at).toLocaleTimeString()}.</p></div>
    <div className="dashboard-grid"><div className="panel"><div className="section-heading"><div><h2>Clustered competitor map</h2><p>Blue dots show exact clusters; the heat layer shows competitor density.</p></div></div><SiteMap location={location} competitors={analysis.competitors} /></div><div className="panel chart-panel"><h2>Monthly cost allocation</h2><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={costs} dataKey="value" nameKey="name" innerRadius={62} outerRadius={96}>{costs.map(item => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip formatter={value => nzd(Number(value))} /></PieChart></ResponsiveContainer><table className="data-table"><tbody>{costs.map(item => <tr key={item.name}><th>{item.name}</th><td>{nzd(item.value)}</td></tr>)}</tbody></table></div></div>
    <div className="bottom-panels"><div className="panel projection-panel"><h2>12-month future profit projection</h2><p>Early months ramp up, then follow the model’s seasonal assumptions.</p><ResponsiveContainer width="100%" height={300}><BarChart data={analysis.profit_projection}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" tickFormatter={value => `M${value}`} /><YAxis tickFormatter={value => `${Math.round(value / 1000)}k`} /><Tooltip formatter={value => nzd(Number(value))} /><Bar dataKey="profit">{analysis.profit_projection.map(item => <Cell key={item.month} fill={item.profit >= 0 ? "#0F766E" : "#EA580C"} />)}</Bar></BarChart></ResponsiveContainer></div><div className="panel details-panel"><h2>Nearby competition summary</h2><div className="distance-bands"><span>Under 100 m <strong>{distanceBands.close}</strong></span><span>100–500 m <strong>{distanceBands.nearby}</strong></span><span>500 m–1.5 km <strong>{distanceBands.wider}</strong></span></div><table className="data-table"><tbody>{nearest.map(item => <tr key={item.id}><th>{item.name}</th><td>{Math.round(item.distance_m)} m</td></tr>)}</tbody></table><h2 className="summary-heading">Financial summary</h2><div className="details-table"><div><span>Monthly rent used</span><strong>{nzd(analysis.rent_cost)}</strong></div><div><span>Estimated monthly profit</span><strong>{nzd(analysis.central_estimate - analysis.total_cost)}</strong></div></div><p className="rent-caption">Unless manually overridden, rent is estimated from the site’s distance to Auckland CBD and a typical floor area for this business type.</p></div></div>
  </section></main>;
}
